Develop
pet-doctor/EmoloyeeService pull request #1
Opened 2023-02-18 09:26 UTC by Gvozdoslav

2023-02-21 16:00 UTC, AlexBossov requested changes

2023-02-21 16:00 UTC, AlexBossov commented on src/main/java/com/petdoctor/employee/model/dto/DoctorDto.java
> +    private DoctorCategory category;
либо как в DoctorEntity doctorCategory, либо там поменять

2023-02-21 16:00 UTC, AlexBossov commented on src/main/java/com/petdoctor/employee/tool/mapper/DoctorMapper.java
>      DoctorDto doctorEntityToDoctorDto(DoctorEntity doctor);
doctorEntity?

2023-02-21 16:00 UTC, AlexBossov commented on src/main/java/com/petdoctor/employee/repository/DoctorRepository.java
> +    @Query(value =
"""
words
"""

2023-02-23 13:28 UTC, Gvozdoslav commented on src/main/java/com/petdoctor/employee/repository/DoctorRepository.java
> +    @Query(value =
nenene))))

2023-03-05 21:35 UTC, merged